// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcPcOrzfjdVzFrXQDoFvWEjBPRCKH5he4',
    appId: '1:402702030710:web:3cf809bab3ac425a358c57',
    messagingSenderId: '402702030710',
    projectId: 'techstartup-outfly',
    authDomain: 'techstartup-outfly.firebaseapp.com',
    storageBucket: 'techstartup-outfly.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1G2CBsu77YX8mDKLfuOlaCoKc-0Q8LgY',
    appId: '1:402702030710:android:2fa5d017f410feed358c57',
    messagingSenderId: '402702030710',
    projectId: 'techstartup-outfly',
    storageBucket: 'techstartup-outfly.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBudVCUsXaV0FHOadc1mXamRPDuhsGLFkI',
    appId: '1:402702030710:ios:fb1745bf39b01eea358c57',
    messagingSenderId: '402702030710',
    projectId: 'techstartup-outfly',
    storageBucket: 'techstartup-outfly.appspot.com',
    iosBundleId: 'np.com.subediabishek.outfly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBudVCUsXaV0FHOadc1mXamRPDuhsGLFkI',
    appId: '1:402702030710:ios:d2ab332a66b2562e358c57',
    messagingSenderId: '402702030710',
    projectId: 'techstartup-outfly',
    storageBucket: 'techstartup-outfly.appspot.com',
    iosBundleId: 'np.com.subediabishek.outfly.RunnerTests',
  );
}
